# Generated by Django 5.0.2 on 2024-02-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='images/')),
                ('title', models.CharField(default='picture', max_length=200)),
                ('first_name', models.CharField(default='', max_length=20)),
                ('second_name', models.CharField(default='', max_length=20)),
                ('first_value', models.FloatField(default=0)),
                ('second_value', models.FloatField(default=0)),
            ],
        ),
    ]
